name: Build and Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
      
    - name: Make build
      run: make all

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: built-binary
        path: bin/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: built-binary
        path: bin/

    - name: Run uds_server tests
      run: |
        chmod +x ./bin/uds_server/tests/test_entrypoint
        ./bin/uds_server/tests/test_entrypoint

    - name: Run uds_handlers tests
      run: |
        chmod +x ./bin/uds_handlers/tests/test_entrypoint
        ./bin/uds_handlers/tests/test_entrypoint
    
